[package]
name = "solarscuffle-bot/tweenutil"
version = "2.0.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

description = "A lot of helpful utilities for reducing the amount of boilerplate tween code in codebases."

[dependencies]
